# Generated by Django 2.2.7 on 2019-11-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_photo', models.ImageField(default=None, max_length=200, upload_to='', verbose_name='Моё фото')),
                ('my_class', models.CharField(default=None, max_length=200, verbose_name='Мой класс')),
                ('my_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('my_age', models.CharField(default=None, max_length=200, verbose_name='Мой возраст')),
                ('language', models.CharField(default=None, max_length=200, verbose_name='Язык программирования')),
                ('my_exp', models.CharField(max_length=200, verbose_name='Мой опыт программирования')),
                ('my_start', models.DateField(verbose_name='Когда я начал программировать')),
                ('add', models.TextField(verbose_name='Дополнительно')),
            ],
        ),
    ]
