# Generated by Django 2.2.7 on 2019-12-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutaway', '0004_auto_20191130_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myexperience',
            name='background',
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='date_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='language',
            field=models.CharField(max_length=200, verbose_name='Язык программирования'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='my_age',
            field=models.CharField(max_length=200, verbose_name='Мой возраст'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='my_class',
            field=models.CharField(max_length=200, verbose_name='Мой класс'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='my_exp',
            field=models.CharField(max_length=200, verbose_name='Мой опыт программирования'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='my_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='my_photo',
            field=models.ImageField(max_length=200, upload_to='image', verbose_name='Моё фото'),
        ),
    ]
