# Generated by Django 2.2.7 on 2019-11-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutaway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myexperience',
            name='my_start',
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='add',
            field=models.TextField(default='Я живу в Зеленограде, а учусь в школе № 1557 имени П. Л. Капицы \n    по направлению "IT". У меня 4 урока программирования, и 4 информатики, 28.11 у нас начался курс web программирования. \n    Ещё нам обещали курс java, но про него ещё ничего не известно. Я начал курс по java на stepik.', verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='date_birth',
            field=models.DateField(default='14.07.2003', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='language',
            field=models.CharField(default='python', max_length=200, verbose_name='Язык программирования'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='my_age',
            field=models.CharField(default='16 лет', max_length=200, verbose_name='Мой возраст'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='my_class',
            field=models.CharField(default='10Д', max_length=200, verbose_name='Мой класс'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='my_exp',
            field=models.CharField(default='2 года', max_length=200, verbose_name='Мой опыт программирования'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='my_name',
            field=models.CharField(default='Малинкин Андрей Дмитриевич', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='my_photo',
            field=models.ImageField(default='my_photo.jpg', max_length=200, upload_to='', verbose_name='Моё фото'),
        ),
    ]
